name: VGF Administrative Services
favicon: null
layout_spectrum: 0
typography_spectrum: 0.64801
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#b8b2b2'
    - '#707070'
    - '#282828'
  brandStrength: 0.5
  lightness: 0.8963153089862317
  saturation: 0.3125
  rhythmicContrast: 0.17820164281874895
purpose: []
